var ksList = {
	'Sinfest':{
		'domain':"sinfest.net",
		'path':"/view.php",
		'shortcuts':{
			'Right':$("img[src='../images/next.gif']").parent()[0],
			'Left':$("img[src='../images/prev.gif']").parent()[0]
		}
	},
	'CAD':{
		'domain':"www.cad-comic.com",
		'path':"/cad/",
		'shortcuts':{
			'Right':$("a.nav-next")[0],
			'Left':$("a.nav-back")[0]
		}
	},
	'CADsillies':{
		'domain':"www.cad-comic.com",
		'path':"/sillies/",
		'shortcuts':{
			'Right':$("a.nav-next")[0],
			'Left':$("a.nav-back")[0]
		}
	},
	'XKCD':{
		'domain':"xkcd.com",
		'shortcuts':{
			'Right':$("a[rel='next']")[0],
			'Left':$("a[rel='prev']")[0]
		}
	},
	'AwkwardZombie':{
		'domain':"www.awkwardzombie.com",
		'shortcuts':{
			'Right':$("img[alt='Next Comic']").parent()[0],
			'Left':$("img[alt='Previous Comic']").parent()[0]
		}
	},
	'Oglaf':{
		'domain':"oglaf.com",
		'shortcuts':{
			'Right':$("div#nx").parent()[0],
			'Left':$("div#pvs").parent()[0]
		}
	},
	'SamAndFuzzy':{
		'domain':"samandfuzzy.com",
		'shortcuts':{
			'Right':$("li.next-page>a")[0],
			'Left':$("li.prev-page>a")[0]
		}
	},
	'PennyArcade':{
		'domain':"penny-arcade.com",
		'path':"/comic/",
		'shortcuts':{
			'Right':$("a.btnNext")[0],
			'Left':$("a.btnPrev")[0]
		}
	},
	'LFG':{
		'domain':"lfgcomic.com",
		'path':"/page/",
		'shortcuts':{
			'Right':null,
			'Left':$("div#comic-left>a")[0]
		}
	},
	'LeastICouldDo':{
		'domain':"leasticoulddo.com",
		'path':"/comic/",
		'shortcuts':{
			'Right':$("a#nav-large-next")[0],
			'Left':$("a#nav-large-prev")[0]
		}
	},
	'PVP':{
		'domain':"pvponline.com",
		'path':"/comic/",
		'shortcuts':{
			'Right':$("div.comic-nav>a")[1],
			'Left':$("div.comic-nav>a")[0]
		}
	},
	'Misfile':{
		'domain':"misfile.com",
		'shortcuts':{
			'Right':$("div#navtop img[alt='Next Comic']").parent()[0],
			'Left':$("div#navtop img[alt='Previous Comic']").parent()[0]
		}
	},
	'GirlsWithSlingshots':{
		'domain':"girlswithslingshots.com",
		'shortcuts':{
			'Right':$("a[rel='next']")[0],
			'Left':$("a[rel='prev']")[0]
		}
	},
	'TwoLumps':{
		'domain':"twolumps.net",
		'shortcuts':{
			'Right':$("a[rel='next']")[0],
			'Left':$("a[rel='prev']")[0]
		}
	},
	'chainsawsuit':{
		'domain':"chainsawsuit.com",
		'shortcuts':{
			'Right':$("img[alt='next']").parent()[0],
			'Left':$("img[alt='previous']").parent()[0]
		}
	},
	'DaveTheDireman':{
		'domain':"direman.com",
		'shortcuts':{
			'Right':$("a:contains('Next')")[0],
			'Left':$("a:contains('Previous')")[0]
		}
	},
	'ScenesFromAMultiverse':{
		'domain':"amultiverse.com",
		'shortcuts':{
			'Right':$("a.navi-next")[0],
			'Left':$("a.navi-prev")[0]
		}
	},
	'DrMcNinja':{
		'domain':"drmcninja.com",
		'shortcuts':{
			'Right':$("a.next")[0],
			'Left':$("a.prev")[0]
		}
	},
	'GunnerkriggCourt':{
		'domain':"gunnerkrigg.com",
		'shortcuts':{
			'Right':$("img[src='http://www.gunnerkrigg.com/images/next_a.jpg']").parent()[0],
			'Left':$("img[src='http://www.gunnerkrigg.com/images/prev_a.jpg']").parent()[0]
		}
	},
	'Candi':{
		'domain':"candicomics.com",
		'shortcuts':{
			'Right':$("a[rel='next']")[0],
			'Left':$("a[rel='prev']")[0]
		}
	},
	'ThreePanelSoul':{
		'domain':"threepanelsoul.com",
		'shortcuts':{
			'Right':$("a[rel='next']")[0],
			'Left':$("a[rel='prev']")[0]
		}
	},
	'Shortpacked':{
		'domain':"shortpacked.com",
		'shortcuts':{
			'Right':$("a[rel='next']")[0],
			'Left':$("a[rel='prev']")[0]
		}
	},
	'DumbingOfAge':{
		'domain':"dumbingofage.com",
		'shortcuts':{
			'Right':$("a.navi-next")[0],
			'Left':$("a.navi-prev")[0]
		}
	},
	'MenageA3':{
		'domain':"ma3comic.com",
		'shortcuts':{
			'Right':$("a#cndnext")[0],
			'Left':$("img[alt='Previous comic']").parent()[0]
		}
	},
	'Buttersafe':{
		'domain':"buttersafe.com",
		'shortcuts':{
			'Right':$("a[rel='next']")[0],
			'Left':$("a[rel='prev']")[0]
		}
	},
	'DarwinCarmichaelIsGoingToHell':{
		'domain':"dcisgoingtohell.com",
		'shortcuts':{
			'Right':$("a.navi-next")[0],
			'Left':$("a.navi-prev")[0]
		}
	},
	'TwoKinds':{
		'domain':"twokinds.keenspot.com",
		'shortcuts':{
			'Right':$("a.navnext,a#cg_next,a#cg_last")[0],
			'Left':$("a.navprev,a#cg_back")[0]
		}
	},
	'DresdenCodak':{
		'domain':"dresdencodak.com",
		'shortcuts':{
			'Right':$("img[src='http://dresdencodak.com_m_next.png']").parent()[0],
			'Left':$("div#preview>a,div.menunav>a")[0]
		}
	},
	'OrderOfTheStick':{
		'domain':"giantitp.com",
		'shortcuts':{
			'Right':$("img[alt='Next Comic']").parent()[0],
			'Left':$("img[alt='Previous Comic']").parent()[0]
		}
	},
	'WastedTalent':{
		'domain':"wastedtalent.ca",
		'shortcuts':{
			'Right':$("a.comic_next")[0],
			'Left':$("a.comic_prev")[0]
		}
	},
	'DarthsAndDroids':{
		'domain':"darthsanddroids.net",
		'shortcuts':{
			'Right':$("div.center>p>a.darth:contains('NEXT>')")[0],
			'Left':$("div.center>p>a.darth:contains('<PREVIOUS')")[0]
		}
	}
}
ksf.apply(ksList);